name: API Contactos CI/CD

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_BASE_NAME: rafaelgomez/contactosapi

jobs:
  API_Image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Mostrar archivos
        run: ls -la

      - name: Build Docker NET image
        run: docker build --platform linux -t $IMAGE_BASE_NAME .
        working-directory: ContactosApi
