name: API Contactos CI/CD

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_BASE_NAME: rafaelgomez/contactosapi

jobs:
  API_Image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker NET image
        run: | 
          docker build --platform linux -t $IMAGE_BASE_NAME:latest .
        working-directory: .

      - name: Push Docker image to Docker Hub
        run: docker push $IMAGE_BASE_NAME:latest
        working-directory: .
